project:
  type: website
  output-dir: docs

website:
  title: "iJustin"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - FRC.qmd
      - contact.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true



